### ISSUE TITLE
posts index view change scrollable

### ISSUE THREAD

**Issue by yomizo** [yomizo/respect-app#15]

**Comment by yomizo** [comment]
- solution is all css

```css
.sidebar {
    height: 100vh
    overflow-y: scroll
}
```
